#!/usr/bin/env sh
#!/usr/bin/with-contenv sh
#shellcheck shell=sh

#mkdir -p /run/s6/services/app/RomVault3_1.Cache
#chown -vR $USER_ID:$GROUP_ID /run/s6/services/app

ln -s /config /romvault

APP_NAME="RomVault ($(grep romvault /VERSIONS | cut -d' ' -f2)) /config"

echo "<Name>${APP_NAME}</Name>" >> /etc/openbox/main-window-selection.xml